# Template Configuration for New Test Suite
# Copy this file and customize for your application

suite_info:
  name: "Your Application Name"
  base_url: "https://your-app.com"
  description: "Description of your application"
  version: "1.0.0"

# Browser configuration
browser:
  default: "chrome"
  headless: false
  window_size: "1920,1080"
  timeout: 30
  options:
    - "--disable-gpu"
    - "--disable-extensions"

# AI feature toggles - customize based on your needs and budget
ai_features:
  self_healing: true          # Auto-fix broken locators
  visual_testing: false       # AI-powered image comparison (costs more)
  test_generation: true       # Generate test cases from page objects
  test_analysis: true         # Analyze test results for insights

# AI model and API settings
ai_settings:
  model: "models/gemini-2.5-flash-lite"  # Cost-effective model
  fallback_models:
    - "models/gemini-2.0-pro"
  max_retries: 3
  initial_retry_delay: 2.0
  max_retry_delay: 60
  enable_caching: true        # Reduce API calls
  cache_ttl: 3600            # 1 hour cache
  visual_threshold: 0.9       # Visual similarity threshold
  temperature: 0.3           # Consistency vs creativity
  top_p: 0.9
  max_tokens: 2048

# Test execution settings
test_execution:
  parallel: false            # Enable for faster execution
  max_workers: 2             # Adjust based on your system
  timeout: 300               # Test timeout in seconds
  retry_failed: false
  
# Reporting configuration
reporting:
  formats:
    - "html"
    - "json"
  include_screenshots: true
  include_ai_analysis: true
  timestamp_format: "%Y%m%d_%H%M%S"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "your_app_tests.log"
  console: true

# Page-specific settings
pages:
  default_timeout: 10
  screenshot_on_failure: true
  auto_scroll: true
  
# Test data settings
test_data:
  generate_realistic: true
  data_locale: "en_US"
  seed: 42

# Visual testing specific settings (if enabled)
visual_testing:
  baseline_directory: "screenshots/baselines/your_app"
  diff_directory: "screenshots/diffs"
  highlight_differences: true
  save_actual_images: true
